# Generated by Django 4.2.4 on 2023-10-08 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_orders_doornum_alter_category_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='doornum',
        ),
    ]
