# Generated by Django 4.2.4 on 2023-10-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_remove_category_date_of_birth_remove_orders_doornum'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='district',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='doornum',
            field=models.IntegerField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='state',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='street',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='town',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
