# Generated by Django 4.2.4 on 2023-10-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_userprofile_guest_district_guest_doornum_guest_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='town',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
